create extension if not exists vector with schema extensions;

create table public.documents (
  id bigint generated by default as identity primary key,
  content text,
  metadata jsonb default '{}'::jsonb,
  embedding vector(3072)
);

alter table public.documents enable row level security;
